id: A9FACFD20
title: 'RK: Gaṅgottaraparipṛcchā'
type: translation
pechas:
- I8D596BA9
- I908DD8CF
- I5A6567EA
source_metadata:
  languages:
  - zh
  - en
  - bo
  datatype: PlainText
  created_at: 2023-02-08 15:08:08.773043
  last_modified_at: 2023-02-08 15:08:08.773058
alignment_to_base:
  I8D596BA9/F17F: 3E88
  I908DD8CF/12CC: 3E88
  I5A6567EA/6531: 3E88
